// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID   string `json:"id" db:"uid"`
	Name string `json:"name" db:"email"`
}

type AddTodo struct {
	ID   string   `json:"id"`
	Text string   `json:"text"`
	User *AddUser `json:"user"`
}

type AddUser struct {
	Username string `json:"username"`
	Name     string `json:"name"`
}
